image:
  repository: artifactory.dagility.com/docker/dec11-dothemagic-frontend
  tag: latest
  pullPolicy: Always
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-internal
  hosts:
  - host: dec11-dothemagic-frontend-testest.dagility.com
    paths:
    - /
serviceAccount:
  create: false
